import time
timestamp = time.strftime("%H")
print(timestamp)
timestamp = time.strftime("%M")
print(timestamp)
timestamp = time.strftime("%S")
print(timestamp)
timestamp = time.strftime("%y")
print(timestamp)
timestamp = time.strftime("%Y")
print(timestamp)
timestamp = time.strftime("%m")
print(timestamp)
timestamp = time.strftime("%d")
print(timestamp)
timestamp = time.strftime("%a")
print(timestamp)
timestamp = time.strftime("%A")
print(timestamp)
timestamp = time.strftime("%b")
print(timestamp)
timestamp = time.strftime("%B")
print(timestamp)
timestamp = time.strftime("%c")
print(timestamp)
timestamp = time.strftime("%I")
print(timestamp)
timestamp = time.strftime("%j")
print(timestamp)
timestamp = time.strftime("%p")
print(timestamp)
timestamp = time.strftime("%U")
print(timestamp)
timestamp = time.strftime("%u")
print(timestamp)
timestamp = time.strftime("%w")
print(timestamp)
timestamp = time.strftime("%W")
print(timestamp)
timestamp = time.strftime("%x")
print(timestamp)
timestamp = time.strftime("%X")
print(timestamp)
timestamp = time.strftime("%z")
print(timestamp)
timestamp = time.strftime("%Z")
print(timestamp)
timestamp = time.strftime("%G")
print(timestamp)
timestamp = time.strftime("%V")
print(timestamp)
timestamp = time.strftime("%%")
print(timestamp)

