import time

timestamp = time.strftime("%x", time.localtime())  
print(timestamp)
timestamp = time.strftime("%X", time.localtime())
print(timestamp)
timestamp = time.strftime("%h", time.localtime())
print(timestamp)
timestamp = time.strftime("%H", time.localtime())
print(timestamp)
timestamp = time.strftime("%M", time.localtime())
print(timestamp)
timestamp = time.strftime("%S", time.localtime())
print(timestamp)
timestamp = time.strftime("%y", time.localtime())
print(timestamp)
timestamp = time.strftime("%Y", time.localtime())
print(timestamp)
timestamp = time.strftime("%d", time.localtime())
print(timestamp)
timestamp = time.strftime("%D", time.localtime())
print(timestamp)
timestamp = time.strftime("%b", time.localtime())
print(timestamp)
timestamp = time.strftime("%B", time.localtime())
print(timestamp)
timestamp = time.strftime("%I", time.localtime())
print(timestamp)
timestamp = time.strftime("%j", time.localtime())
print(timestamp)
timestamp = time.strftime("%U", time.localtime())
print(timestamp)
